name: agro_care_web
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.3.0
  url_launcher: ^6.2.4
  provider: ^6.1.1
  clipboard: ^0.1.2
  lottie: ^2.3.2
  flutter_quill: ^9.2.10
  quill_html_converter: ^9.2.10
  responsive_builder: ^0.7.0
  intl: ^0.18.1
  
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  firebase_storage: ^11.6.5
  pie_chart: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
